import { 
  Wrench, 
  Zap, 
  PaintRoller, 
  Hammer, 
  Sparkles, 
  ShieldAlert, 
  Tv, 
  Sprout, 
  Wind, 
  Scissors, 
  Truck, 
  HelpCircle 
} from 'lucide-react-native';

export const MOCK_CATEGORIES = [
  { id: 'plumber', name: 'Plumber', icon: Wrench, color: '#3B82F6', desc: 'Leaking pipes, taps, and water tank setup' },
  { id: 'electrician', name: 'Electrician', icon: Zap, color: '#F59E0B', desc: 'Short circuits, fans, lights, and wiring' },
  { id: 'painter', name: 'Painter', icon: PaintRoller, color: '#10B981', desc: 'Wall touch-ups, full home painting, and waterproofing' },
  { id: 'carpenter', name: 'Carpenter', icon: Hammer, color: '#8B5CF6', desc: 'Furniture repair, wood cutting, and door locks' },
  { id: 'cleaning', name: 'Cleaner', icon: Sparkles, color: '#EC4899', desc: 'Deep house cleaning, kitchen and bathroom wash' },
  { id: 'pest_control', name: 'Pest Control', icon: ShieldAlert, color: '#EF4444', desc: 'Termites, cockroaches, and bedbugs disinfection' },
  { id: 'appliance', name: 'Appliance Repair', icon: Tv, color: '#6366F1', desc: 'TV, washing machine, and microwave repairs' },
  { id: 'gardening', name: 'Gardener', icon: Sprout, color: '#84CC16', desc: 'Lawn trimming, potting, and garden maintenance' },
  { id: 'ac_service', name: 'AC Service', icon: Wind, color: '#06B6D4', desc: 'AC filter cleaning, gas filling, and installation' },
  { id: 'salon', name: 'Home Salon', icon: Scissors, color: '#A855F7', desc: 'Haircut, massage, and grooming services at home' },
  { id: 'movers', name: 'Packers & Movers', icon: Truck, color: '#14B8A6', desc: 'Shifting homes, packing, and safe transport' },
  { id: 'others', name: 'Other Services', icon: HelpCircle, color: '#6B7280', desc: 'General labor, masonry, and miscellaneous tasks' },
];

export const MOCK_WORKERS = [
  // Plumber
  { 
    id: 1, 
    name: 'Ramesh Kumar', 
    skill: 'Plumber', 
    rating: 4.8, 
    reviews: 124, 
    distance: '1.2 km', 
    price: '₹400/hr', 
    baseRate: 400, 
    dailyRate: '₹1,500/day', 
    verified: true, 
    about: 'I have 8+ years of experience in all kinds of plumbing works including pipe fitting, water tank installation, and leakage repairs.', 
    reliabilityScore: 98, 
    completedJobs: 342,
    experience: '8 years',
    phone: '+91 98765 43210'
  },
  { 
    id: 5, 
    name: 'Rajesh Gupta', 
    skill: 'Plumber', 
    rating: 4.5, 
    reviews: 42, 
    distance: '4.2 km', 
    price: '₹380/hr', 
    baseRate: 380, 
    dailyRate: '₹1,300/day', 
    verified: false, 
    about: 'Helpful and reliable local plumber. Specialized in bathroom accessories fitting, drain cleaning, and sink installations.', 
    reliabilityScore: 90, 
    completedJobs: 98,
    experience: '3 years',
    phone: '+91 98765 43214'
  },
  // Electrician
  { 
    id: 2, 
    name: 'Suresh Singh', 
    skill: 'Electrician', 
    rating: 4.9, 
    reviews: 98, 
    distance: '2.5 km', 
    price: '₹450/hr', 
    baseRate: 450, 
    dailyRate: '₹1,800/day', 
    verified: true, 
    about: 'Master electrician certified in industrial and home wiring. Specialized in resolving short circuits and installing appliances.', 
    reliabilityScore: 99, 
    completedJobs: 412,
    experience: '9 years',
    phone: '+91 98765 43211'
  },
  { 
    id: 11, 
    name: 'Anil Verma', 
    skill: 'Electrician', 
    rating: 4.6, 
    reviews: 29, 
    distance: '1.9 km', 
    price: '₹420/hr', 
    baseRate: 420, 
    dailyRate: '₹1,500/day', 
    verified: false, 
    about: 'Expert in residential wiring, fan/switch repair, and wall light fixtures. Quick service and guaranteed safety.', 
    reliabilityScore: 94, 
    completedJobs: 78,
    experience: '4 years',
    phone: '+91 98765 43231'
  },
  // Painter
  { 
    id: 3, 
    name: 'Amit Sharma', 
    skill: 'Painter', 
    rating: 4.7, 
    reviews: 56, 
    distance: '3.1 km', 
    price: '₹350/hr', 
    baseRate: 350, 
    dailyRate: '₹1,400/day', 
    verified: false, 
    about: 'Professional home painter with a keen eye for detail. Expertise in wall touch-ups, textured painting, and exterior coatings.', 
    reliabilityScore: 92, 
    completedJobs: 189,
    experience: '5 years',
    phone: '+91 98765 43212'
  },
  { 
    id: 12, 
    name: 'Dilip Kumar', 
    skill: 'Painter', 
    rating: 4.8, 
    reviews: 84, 
    distance: '2.3 km', 
    price: '₹390/hr', 
    baseRate: 390, 
    dailyRate: '₹1,600/day', 
    verified: true, 
    about: 'Interior wall styling, wood polishing, wall-putty applications, and water leak proofing. Highly experienced team.', 
    reliabilityScore: 96, 
    completedJobs: 245,
    experience: '7 years',
    phone: '+91 98765 43232'
  },
  // Carpenter
  { 
    id: 4, 
    name: 'Vikram Lohar', 
    skill: 'Carpenter', 
    rating: 4.6, 
    reviews: 73, 
    distance: '1.8 km', 
    price: '₹500/hr', 
    baseRate: 500, 
    dailyRate: '₹2,000/day', 
    verified: true, 
    about: 'Specialized in modular kitchen installations, custom wardrobes, and repairing old wooden furniture. Punctual and precise.', 
    reliabilityScore: 95, 
    completedJobs: 231,
    experience: '6 years',
    phone: '+91 98765 43213'
  },
  { 
    id: 13, 
    name: 'Harish Mistry', 
    skill: 'Carpenter', 
    rating: 4.7, 
    reviews: 48, 
    distance: '3.0 km', 
    price: '₹480/hr', 
    baseRate: 480, 
    dailyRate: '₹1,900/day', 
    verified: false, 
    about: 'Wooden door setups, latch/lock repairs, dining table modifications, and general wooden carpentry repairs.', 
    reliabilityScore: 93, 
    completedJobs: 112,
    experience: '5 years',
    phone: '+91 98765 43233'
  },
  // Cleaner
  { 
    id: 6, 
    name: 'Priyanka Sen', 
    skill: 'Cleaner', 
    rating: 4.9, 
    reviews: 145, 
    distance: '0.9 km', 
    price: '₹300/hr', 
    baseRate: 300, 
    dailyRate: '₹1,000/day', 
    verified: true, 
    about: 'Expert in residential and office deep cleaning. Equipped with eco-friendly cleaning supplies and sanitization tools.', 
    reliabilityScore: 98, 
    completedJobs: 512,
    experience: '7 years',
    phone: '+91 98765 43215'
  },
  { 
    id: 14, 
    name: 'Maya Devi', 
    skill: 'Cleaner', 
    rating: 4.7, 
    reviews: 67, 
    distance: '2.8 km', 
    price: '₹280/hr', 
    baseRate: 280, 
    dailyRate: '₹950/day', 
    verified: true, 
    about: 'Specialized in kitchen oil stain cleaning, bathroom tiles scrub-wash, and sofa/carpet shampoo washing.', 
    reliabilityScore: 95, 
    completedJobs: 180,
    experience: '4 years',
    phone: '+91 98765 43234'
  },
  // Pest Control
  { 
    id: 7, 
    name: 'Mohit Varma', 
    skill: 'Pest Control', 
    rating: 4.8, 
    reviews: 62, 
    distance: '2.1 km', 
    price: '₹600/hr', 
    baseRate: 600, 
    dailyRate: '₹2,200/day', 
    verified: true, 
    about: 'Certified pest control professional. Safe chemical treatment for cockroaches, bedbugs, termites, and rodents with a warranty.', 
    reliabilityScore: 96, 
    completedJobs: 174,
    experience: '5 years',
    phone: '+91 98765 43216'
  },
  { 
    id: 15, 
    name: 'Sanjay Patil', 
    skill: 'Pest Control', 
    rating: 4.6, 
    reviews: 35, 
    distance: '3.8 km', 
    price: '₹550/hr', 
    baseRate: 550, 
    dailyRate: '₹2,000/day', 
    verified: false, 
    about: 'Provide organic pest control solutions safe for pets and children. Specialized in cockroach gel and mosquito fogging treatment.', 
    reliabilityScore: 91, 
    completedJobs: 89,
    experience: '3 years',
    phone: '+91 98765 43235'
  },
  // Appliance Repair
  { 
    id: 16, 
    name: 'Vivek Roy', 
    skill: 'Appliance Repair', 
    rating: 4.7, 
    reviews: 52, 
    distance: '2.8 km', 
    price: '₹400/hr', 
    baseRate: 400, 
    dailyRate: '₹1,500/day', 
    verified: true, 
    about: 'Expert technician for Microwave oven, washing machine, TV, and Refrigerator repairs. Original spare parts guaranteed.', 
    reliabilityScore: 95, 
    completedJobs: 142,
    experience: '6 years',
    phone: '+91 98765 43236'
  },
  { 
    id: 17, 
    name: 'Sandeep Joshi', 
    skill: 'Appliance Repair', 
    rating: 4.5, 
    reviews: 31, 
    distance: '3.4 km', 
    price: '₹350/hr', 
    baseRate: 350, 
    dailyRate: '₹1,300/day', 
    verified: false, 
    about: 'Specialized in repairing top load and front load washing machines, refrigerators, and induction stoves.', 
    reliabilityScore: 89, 
    completedJobs: 67,
    experience: '4 years',
    phone: '+91 98765 43237'
  },
  // Gardener
  { 
    id: 18, 
    name: 'Ramlal Mali', 
    skill: 'Gardener', 
    rating: 4.8, 
    reviews: 64, 
    distance: '1.0 km', 
    price: '₹250/hr', 
    baseRate: 250, 
    dailyRate: '₹900/day', 
    verified: true, 
    about: 'Lawn styling, trimming, weed removal, plant medicine spray, and kitchen garden planting setups. Passionate about green spaces.', 
    reliabilityScore: 97, 
    completedJobs: 215,
    experience: '8 years',
    phone: '+91 98765 43238'
  },
  { 
    id: 19, 
    name: 'Shyam Lal', 
    skill: 'Gardener', 
    rating: 4.6, 
    reviews: 22, 
    distance: '2.7 km', 
    price: '₹200/hr', 
    baseRate: 200, 
    dailyRate: '₹800/day', 
    verified: false, 
    about: 'Balcony garden setup, flower potting, soil replacement, and regular garden pruning maintenance.', 
    reliabilityScore: 92, 
    completedJobs: 54,
    experience: '3 years',
    phone: '+91 98765 43239'
  },
  // AC Service
  { 
    id: 8, 
    name: 'Karan Malhotra', 
    skill: 'AC Service', 
    rating: 4.7, 
    reviews: 81, 
    distance: '1.5 km', 
    price: '₹450/hr', 
    baseRate: 450, 
    dailyRate: '₹1,700/day', 
    verified: true, 
    about: 'AC repair and maintenance expert. Quick servicing, gas refilling, and leakage fixes for both split and window AC units.', 
    reliabilityScore: 94, 
    completedJobs: 215,
    experience: '4 years',
    phone: '+91 98765 43217'
  },
  { 
    id: 20, 
    name: 'Vinay Bajpai', 
    skill: 'AC Service', 
    rating: 4.8, 
    reviews: 43, 
    distance: '2.4 km', 
    price: '₹480/hr', 
    baseRate: 480, 
    dailyRate: '₹1,800/day', 
    verified: true, 
    about: 'AC dismantling, new AC installations, condenser replacement, and high-pressure jet wash filter cleaning.', 
    reliabilityScore: 96, 
    completedJobs: 95,
    experience: '5 years',
    phone: '+91 98765 43240'
  },
  // Home Salon
  { 
    id: 9, 
    name: 'Sunita Rao', 
    skill: 'Home Salon', 
    rating: 4.9, 
    reviews: 110, 
    distance: '1.7 km', 
    price: '₹500/hr', 
    baseRate: 500, 
    dailyRate: '₹2,500/day', 
    verified: true, 
    about: 'Professional beautician offering haircut, facial, waxing, and massage services in the comfort of your home. Premium hygiene standards.', 
    reliabilityScore: 97, 
    completedJobs: 290,
    experience: '6 years',
    phone: '+91 98765 43218'
  },
  { 
    id: 21, 
    name: 'Ritu Sharma', 
    skill: 'Home Salon', 
    rating: 4.7, 
    reviews: 58, 
    distance: '2.9 km', 
    price: '₹450/hr', 
    baseRate: 450, 
    dailyRate: '₹2,000/day', 
    verified: false, 
    about: 'Makeup, bridal grooming, facial treatments, hair oil massage, pedicure and manicure. Uses premium brand products.', 
    reliabilityScore: 93, 
    completedJobs: 130,
    experience: '4 years',
    phone: '+91 98765 43241'
  },
  // Packers & Movers
  { 
    id: 10, 
    name: 'Devender Yadav', 
    skill: 'Packers & Movers', 
    rating: 4.6, 
    reviews: 38, 
    distance: '3.5 km', 
    price: '₹800/hr', 
    baseRate: 800, 
    dailyRate: '₹5,000/day', 
    verified: false, 
    about: 'Experienced loading and shifting handler. Safe bubble wrapping, packing of fragile items, and dynamic transport solutions.', 
    reliabilityScore: 91, 
    completedJobs: 82,
    experience: '3 years',
    phone: '+91 98765 43219'
  },
  { 
    id: 22, 
    name: 'Balaji Movers', 
    skill: 'Packers & Movers', 
    rating: 4.9, 
    reviews: 72, 
    distance: '4.5 km', 
    price: '₹950/hr', 
    baseRate: 950, 
    dailyRate: '₹6,500/day', 
    verified: true, 
    about: 'Top packers and movers service. We provide packing boxes, bubble sheets, and closed container container trucks with complete labor assistance.', 
    reliabilityScore: 98, 
    completedJobs: 198,
    experience: '8 years',
    phone: '+91 98765 43242'
  },
  // Other Services
  { 
    id: 23, 
    name: 'Gopal Yadav', 
    skill: 'Other Services', 
    rating: 4.4, 
    reviews: 18, 
    distance: '1.5 km', 
    price: '₹180/hr', 
    baseRate: 180, 
    dailyRate: '₹750/day', 
    verified: false, 
    about: 'Available for loading/unloading boxes, domestic helper assistance, wall drilling, and general helpers tasks.', 
    reliabilityScore: 90, 
    completedJobs: 43,
    experience: '2 years',
    phone: '+91 98765 43243'
  },
  { 
    id: 24, 
    name: 'Shankar Mason', 
    skill: 'Other Services', 
    rating: 4.7, 
    reviews: 45, 
    distance: '2.9 km', 
    price: '₹300/hr', 
    baseRate: 300, 
    dailyRate: '₹1,200/day', 
    verified: true, 
    about: 'Expert brick mason. Tile replacement, kitchen platform repairs, concrete wall touch-ups, and plaster repairs.', 
    reliabilityScore: 96, 
    completedJobs: 114,
    experience: '5 years',
    phone: '+91 98765 43244'
  }
];
